Repository FacundoGerv/rgb-soft, pull requests merged in 2023-11, with the labels that each got.

#19 update 4.1.2
  src/App.js
  src/GlobalContext.js
  src/Navbar.js
  src/ProductViews/Home.js
  src/ProductViews/addproduct.js
  src/ProductViews/iphone.js
  src/images/addproduct.png
  src/images/logout.png
  src/index.js
  src/styles/Navbar.css
  src/styles/addprod.css
Labels: enhancement, Visual update, bugfix

#22 update 4.1.3
  src/ProductViews/iphone.js
  src/images/edit.png
  src/images/tick.png
  src/styles/Navbar.css
  src/styles/Products.css
Labels: enhancement

#27 Delete public directory
  package-lock.json
  package.json
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.js
  src/App.test.js
  src/GlobalContext.js
  src/Navbar.js
  src/ProductViews/Home.js
  src/ProductViews/accesorios.js
  src/ProductViews/addproduct.js
  src/ProductViews/airpods.js
  src/ProductViews/applewatch.js
  src/ProductViews/cargadores.js
  src/ProductViews/iphone.js
  src/ProductViews/stock.js
  src/TempData.json
  src/images/addproduct.png
  src/images/airpods.png
  src/images/back-icon.png
  src/images/charger-icon.png
  src/images/contact-icon.png
  src/images/edit.png
  src/images/iphone-case.png
  src/images/iphone-icon.png
  src/images/iwatch-icon.png
  src/images/logo.svg
  src/images/logo512.png
  src/images/logout.png
  src/images/prueba1.jpg
  src/images/prueba2.jpg
  src/images/prueba3.jpg
  src/images/sidebar-close-icon.png
  src/images/sidebar-menu-icon.png
  src/images/sidebar-open-icon.png
  src/images/softLogo.png
  src/images/tick.png
  src/images/whatsapp.png
  src/index.js
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/App.css
  src/styles/Home.css
  src/styles/Navbar.css
  src/styles/Products.css
  src/styles/addprod.css
  src/styles/index.css
Labels: Folder/files issues

#28 Front update alpha 1.0
  Frontend/README.md
  Frontend/package.json
  Frontend/public/index.html
  Frontend/public/manifest.json
  Frontend/public/robots.txt
  Frontend/src/App.js
  Frontend/src/App.test.js
  Frontend/src/GlobalContext.js
  Frontend/src/Navbar.js
  Frontend/src/ProductViews/Home.js
  Frontend/src/ProductViews/accesorios.js
  Frontend/src/ProductViews/addproduct.js
  Frontend/src/ProductViews/airpods.js
  Frontend/src/ProductViews/applewatch.js
  Frontend/src/ProductViews/cargadores.js
  Frontend/src/ProductViews/iphone.js
  Frontend/src/ProductViews/stock.js
  Frontend/src/TempData.json
  Frontend/src/images/addproduct.png
  Frontend/src/images/airpods.png
  Frontend/src/images/back-icon.png
  Frontend/src/images/charger-icon.png
  Frontend/src/images/contact-icon.png
  Frontend/src/images/edit.png
  Frontend/src/images/iphone-case.png
  Frontend/src/images/iphone-icon.png
  Frontend/src/images/iwatch-icon.png
  Frontend/src/images/logo.svg
  Frontend/src/images/logo512.png
  Frontend/src/images/logout.png
  Frontend/src/images/prueba1.jpg
  Frontend/src/images/prueba2.jpg
  Frontend/src/images/prueba3.jpg
  Frontend/src/images/sidebar-close-icon.png
  Frontend/src/images/sidebar-menu-icon.png
  Frontend/src/images/sidebar-open-icon.png
  Frontend/src/images/softLogo.png
  Frontend/src/images/tick.png
  Frontend/src/images/whatsapp.png
  Frontend/src/index.js
  Frontend/src/reportWebVitals.js
  Frontend/src/setupTests.js
  Frontend/src/styles/App.css
  Frontend/src/styles/Home.css
  Frontend/src/styles/Navbar.css
  Frontend/src/styles/Products.css
  Frontend/src/styles/addprod.css
  Frontend/src/styles/index.css
Labels: Folder/files issues
