Repository FacundoGerv/rgb-soft, pull requests merged in 2023-10, with the labels that each got.

#5 Update 0.2
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.js
  src/App.test.js
  src/ProductViews/iphone.js
  src/images/prueba1.jpg
  src/index.js
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/App.css
  src/styles/Products.css
  src/styles/index.css
Labels: enhancement

#6 Update 0.3
  src/ProductViews/iphone.js
  src/styles/Products.css
Labels: enhancement

#7 update 0.3.1
  src/ProductViews/iphone.js
  src/styles/App.css
  src/styles/Navbar.css
  src/styles/Products.css
Labels: enhancement, Visual update

#8 Update 0.3.1
  src/ProductViews/iphone.js
  src/styles/App.css
  src/styles/Products.css
Labels: enhancement, Visual update, Duplicate

#9 Update 0.3.2
  src/Navbar.js
  src/styles/Navbar.css
Labels: enhancement

#11 Update 4.0
  src/ProductViews/Home.js
  src/ProductViews/accesorios.js
  src/ProductViews/airpods.js
  src/ProductViews/applewatch.js
  src/ProductViews/cargadores.js
  src/ProductViews/iphone.js
  src/styles/Home.css
  src/styles/Products.css
Labels: bug, enhancement, Visual update

#12 update 4.1
  src/Navbar.js
  src/ProductViews/Home.js
  src/ProductViews/applewatch.js
  src/ProductViews/iphone.js
  src/images/airpods.png
  src/images/charger-icon.png
  src/images/contact-icon.png
  src/images/iphone-case.png
  src/images/iphone-icon.png
  src/images/iwatch-icon.png
  src/images/sidebar-close-icon.png
  src/images/sidebar-menu-icon.png
  src/images/sidebar-open-icon.png
  src/styles/Home.css
  src/styles/Navbar.css
  src/styles/Products.css
Labels: enhancement, Visual update

#13 Update-4.1
  src/ProductViews/iphone.js
  src/images/back-icon.png
  src/images/prueba1.jpg
  src/images/prueba2.jpg
  src/images/prueba3.jpg
  src/images/whatsapp.png
  src/styles/Products.css
Labels: enhancement, bugfix

#14 update 4.1
  public/manifest.json
  src/App.js
  src/Navbar.js
  src/ProductViews/Home.js
  src/ProductViews/iphone.js
  src/index.js
  src/styles/Home.css
  src/styles/index.css
Labels: enhancement, Visual update

#16 update 4.1.1
  src/App.js
  src/Navbar.js
  src/ProductViews/Home.js
  src/ProductViews/iphone.js
  src/styles/App.css
  src/styles/Home.css
  src/styles/Navbar.css
  src/styles/Products.css
  src/styles/index.css
Labels: enhancement, Visual update, bugfix
